### ISSUE TITLE
Test mails should be populated before the connection is closed

### ISSUE THREAD

**Issue by rmartz00** [adscott/mailcrate#9]
Because Mailcrate does not populate `@mails` until after the connection is closed, there is a possibility that the sent mail is not there by the time the test is attempting to access it. This can be avoided on the test side with a wait after the delivery until a mail in `@mails` is detected, but could potentially be fixed in mailcrate itself by putting [this](https://github.com/adscott/mailcrate/blob/master/lib/mailcrate.rb#L88) before the `connection.close`.

This can be reproduced more easily when using `.send(:deliver_now)` rather than calling `deliver_now` directly though it has been reproduced once in the latter case. 

A test like this can cause the issue (in this case a nil error on `mailcrate.mails.last`):
```
    it 'has mail' do
      TestMailer.welcome.send(:deliver_now)
      assert mailcrate.mails.last[:from]
    end
```

**Comment by grosser** [comment]
dammit ... I'm a maintainer here too :(

**Comment by grosser** [comment]
fix coming in https://github.com/adscott/mailcrate/pull/10 ... need a hand from @adscott

**Comment by adscott** [comment]
Thanks @grosser. New version published.
